GEN-921 | Update postal address to Tulegatan (#3114)
<!--
PR title: GRW-123 / Feature / Awesome new thing
-->

## Describe your changes


![Screenshot 2023-09-01 at 13.00.16.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/87b42925-79be-4718-8f62-8cb43eb1eb8c/Screenshot%202023-09-01%20at%2013.00.16.png)


- Update postal address in footer + JSON schema

- Refactor address information to come from a single source of truth

- Update MSW helper file

- Exclude ".js" filed from ESLint

<!--
What changes are made?
If there are many changes, a list might be a good format.
If it makes sense, add screenshots and/or screen recordings here.
-->

## Justify why they are needed

- We have moved!

- Need to exclude JS files from ESLint to avoid errors like this:

  ```text
  Error: Error while loading rule '@typescript-eslint/no-unnecessary-condition': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
  ```

## Checklist before requesting a review

- [ ] I have performed a self-review of my code